version: '3.8'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    command: /bin/bash /entrypoint.sh
    env_file:
      - mssql.env
    networks:
      - net
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./service station/db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./service station/db/mssql/docker-db-init.sh:/db-init.sh
      - ./service station/db/mssql/database.sql:/db-init.sql
    healthcheck:
      test: ["CMD","/opt/mssql-tools/bin/sqlcmd", "-Uadmin2", "-PSomeStrongPwd124", "-Q", "select 1"]
      start_period: 30s
      interval: 5s
      retries: 20

  app:

    build: Service Station/
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      mssql:
        condition: service_healthy
    env_file:
      - env.env

networks:
  net:
    driver: bridge
volumes:
  dbdata: