version: '3.8'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    command: /bin/bash /entrypoint.sh
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD : SomeStrongPwd123
      PID : Express
      DATABASE : CarService
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./service station/db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./service station/db/mssql/docker-db-init.sh:/db-init.sh
      - ./service station/db/mssql/database.sql:/db-init.sql
    healthcheck:
      test: ["CMD","/opt/mssql-tools/bin/sqlcmd", "-Uadmin2", "-PSomeStrongPwd124", "-Q", "select 1"]
      interval: 1s
      retries: 20
  app:
    build: Service Station/
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;encrypt=false;database=CarService;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: admin2
      SPRING_DATASOURCE_PASSWORD: SomeStrongPwd124

volumes:
  dbdata: